name = "random-note"
main = "src/worker.js"
compatibility_date = "2024-10-01"
workers_dev = true

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = false

[[kv_namespaces]]
binding = "RECORDS_STORE"
id = "your-kv-id"

[vars]
ALLOWED_ORIGIN = "https://your.worker.url"
JWT_SECRET = "your-secret"